Create method to get subject from the JWT token in the context
There are also tests for this, but one of them only works in the spec file itself, and breaks when using gradlew test. More specifically, it gives a java.lang.NoSuchMethodError at TokenVerifierSpec.java:338, which seems to take issue with ctx.status().

#19